version: "{build}"
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    dotnet restore src/storage.sln

    cd src/Storage.Net

    dotnet housework setbuildnumber %FileVersion%  ../../build.ini -v

    dotnet housework author ../*.csproj  ../../build.ini -r -v

    cd ../..
build:
  project: src/storage.sln
  verbosity: minimal
test_script:
- ps: dotnet test .\src\Storage.Net.Tests\ -c release
artifacts:
- path: src/**/*.nupkg
deploy: off