version: "{build}"
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    dotnet tool install housework -g

    housework setbuildnumber %FileVersion% -s build.ini

    housework author src/*.csproj -s build.ini -r

    dotnet restore src/storage.sln
build:
  project: src/storage.sln
  verbosity: minimal
test_script:
- ps: dotnet test .\src\Storage.Net.Tests\ -c release
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: hQlxhZb6uDjtZz4V+DZyAqjxnGjXqEokO/tckU14RDUP/AxTkFnX869pNsXCv+Ab
  on:
    branch: master